version: '3.9'

services:
  server:
    build: ./app
    ports:
      - '8000:9000'
    environment:
      - PORT=9000
      - PG_PASSWORD=123456
      - PG_HOST=postgres_server
      - PG_USER=admin
      - PG_DB=node_app_pg_db
      - REDIS_HOST=redis_server
      - REDIS_PORT=6379
    depends_on:
      - postgres_server
    links:
      - redis_server
  postgres_server:
    image: 'postgres'
    environment:
      POSTGRES_PASSWORD: '123456'
      POSTGRES_USER: 'admin'
      POSTGRES_DB: 'node_app_pg_db'
    volumes:
      - data:/var/lib/postgresql/data
  redis_server:
    image: redis:alpine
    container_name: redis_server
    restart: unless-stopped
    expose:
      - 6379
volumes:
  data:
